"""update some data

Revision ID: 03213fb77a04
Revises: 1df86f1badd5
Create Date: 2026-01-27 20:52:25.184652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '03213fb77a04'
down_revision: Union[str, Sequence[str], None] = '1df86f1badd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_table('user')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('order_id', sa.VARCHAR(), nullable=False),
    sa.Column('user', sqlite.JSON(), nullable=True),
    sa.Column('restaurant', sqlite.JSON(), nullable=True),
    sa.Column('order', sqlite.JSON(), nullable=True),
    sa.Column('otp', sa.VARCHAR(), nullable=True),
    sa.Column('total_price', sa.FLOAT(), nullable=False),
    sa.Column('is_approved_by_restaurant', sa.BOOLEAN(), nullable=False),
    sa.Column('approved_at', sa.VARCHAR(), nullable=True),
    sa.Column('order_status', sa.VARCHAR(length=11), nullable=True),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('contact', sqlite.JSON(), nullable=True),
    sa.Column('address', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=False),
    sa.Column('order_history', sqlite.JSON(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=1)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    # ### end Alembic commands ###
