"""Add updated_at column to menu

Revision ID: 1df86f1badd5
Revises: 
Create Date: 2026-01-25 19:44:31.820447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df86f1badd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu', sa.Column('updated_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_menu_updated_at'), 'menu', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_updated_at'), table_name='menu')
    op.drop_column('menu', 'updated_at')
    # ### end Alembic commands ###
