"""Fix the Foregin Key Constraint

Revision ID: 4c84c676237a
Revises: 8e067919b97e
Create Date: 2026-02-07 21:27:10.361609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '4c84c676237a'
down_revision: Union[str, Sequence[str], None] = '8e067919b97e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_index(op.f('ix_orders_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_restaurant_created_at'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_name'), table_name='restaurant')
    op.drop_index(op.f('ix_restaurant_restaurant_id'), table_name='restaurant')
    op.drop_table('restaurant')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_updated_at'), table_name='user')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('contact', sqlite.JSON(), nullable=True),
    sa.Column('address', sqlite.JSON(), nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.Column('updated_at', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_updated_at'), 'user', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_table('restaurant',
    sa.Column('restaurant_id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('contact', sqlite.JSON(), nullable=True),
    sa.Column('address', sqlite.JSON(), nullable=True),
    sa.Column('category', sqlite.JSON(), nullable=True),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('restaurant_id')
    )
    op.create_index(op.f('ix_restaurant_restaurant_id'), 'restaurant', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_restaurant_name'), 'restaurant', ['name'], unique=False)
    op.create_index(op.f('ix_restaurant_created_at'), 'restaurant', ['created_at'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.VARCHAR(), nullable=False),
    sa.Column('total_price', sa.NUMERIC(), nullable=False),
    sa.Column('is_approved_by_restaurant', sa.BOOLEAN(), nullable=False),
    sa.Column('approved_at', sa.DATETIME(), nullable=True),
    sa.Column('status', sa.VARCHAR(length=11), nullable=True),
    sa.Column('approval_otp', sa.VARCHAR(), nullable=True),
    sa.Column('order_items', sqlite.JSON(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_snapshot', sqlite.JSON(), nullable=False),
    sa.Column('restaurant_id', sa.INTEGER(), nullable=False),
    sa.Column('restaurant_snapshot', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.restaurant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_orders_order_id'), 'orders', ['order_id'], unique=False)
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    # ### end Alembic commands ###
